note = dict()
note['username'] = (input("Имя пользователя: "))
note['titles'] = [input('Первый заголовок заметки: ')]
note['titles'].append(input('Второй заголовок заметки: '))
note['titles'].append(input('Третий заголовок заметки: '))
note['content'] = input('Описание заметки: ')
note['status'] = input('Статус заметки: ')
note['created_date'] = input("Дата создания заметки в формате 'ДД-ММ-ГГГГ': ")
note['issue_date'] = input("Дата истечения заметки в формате 'ДД-ММ-ГГГГ': ")

print("Имя пользователя:", note['username'])
print('Заголовки заметки', note['titles'])
print('Описание заметки', note['content'])
print('Статус заметки', note['status'])
print('Дата создания заметки', note['created_date'])
print('Дата истечения заметки', note['issue_date'])
